- name: Deploy Azure Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: eastus

    - name: Create a virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: myVNet
        address_prefixes: "10.50.0.0/20"

    - name: Create a subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network_name: myVNet
        name: mySubnet
        address_prefix: "10.50.1.0/24"

    - name: Create a network security group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: myNSG
        rules:
          - name: AllowSSH
            priority: 1001
            direction: Inbound
            access: Allow
            protocol: Tcp
            destination_port_range: 22
            source_address_prefix: "217.147.163.182"
          - name: AllowHTTP
            priority: 1002
            direction: Inbound
            access: Allow
            protocol: Tcp
            destination_port_range: 80
            source_address_prefix: "*"

    - name: Create a public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: myPublicIP
        allocation_method: Static

    - name: Create a network interface
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: myNIC
        virtual_network: myVNet
        subnet_name: mySubnet
        security_group: myNSG
        ip_configurations:
          - name: myNICConfig
            public_ip_name: myPublicIP  # Attach the public IP here

    - name: Create an Ubuntu VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: myNIC
        name: myVM
        vm_size: Standard_B1s
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/ansvm_rsa.pub') }}"
        network_interfaces: myNIC
        image:
          offer: debian-12
          publisher: Debian
          sku: "12"
          version: latest
        state: present

- name: Ensure VM is ready for Ansible
  hosts: azure_serhiihomeniukans
  become: yes
  tasks:
    - name: Install Python 3 if missing
      raw: |
        if ! command -v python3 &>/dev/null; then
          sudo apt update && sudo apt install -y python3
        fi
      changed_when: false

- name: Configure Nginx on VM
  hosts: azure_serhiihomeniukans
  become: yes
  pre_tasks:
    - name: Ensure Python 3 is installed
      raw: sudo apt update && sudo apt install -y python3
      changed_when: false
        
  roles:
    - nginx-config
