- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes    

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Copy custom HTML file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: "0644"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes
